### ISSUE TITLE
Encode multiple categorical variables in a dataframe

### ISSUE THREAD

**Issue by talegari** [JeffJetton/greenclust#7]
Hi Jeff,

Thanks for implementing Greenacre's method in a handy package!

I wrote a R6 class to reduce multiple columns in a dataframe (in parallel) with a `fit` method (based on `greenclust`) and `predict` method on a new dataframe. Let me know if this makes a good contribution and if you are open for a PR.

**Comment by JeffJetton** [comment]
My current intention is to keep greenclust pretty basic and simple. Interesting idea to use it to help reduce columns--might be worth you making it a package in its own right? (Is the source on your github anywhere yet?)

**Comment by talegari** [comment]
1. I understand your intention to keep greenclust simple. I will probably make encoder into a different package.
2. Here is the [code](https://gist.github.com/talegari/b328ea2d7dd1ae9f6b249e8642840186) for the R6 class.
3. Currently, greenclust is written in R completely and might not be fast on large data. Do you have plans to rewrite this with Rcpp or C?

**Comment by JeffJetton** [comment]
3. It's _definitely_ not fast on large data, which is indeed a problem. I might rewrite in C if the package proves popular enough, but my next step is to try some optimization ideas I have in pure R first, to see what gains that gets me.

Thanks for your input, talegari!
